# This is a basic workflow to help you get started with Actions

name: AWS Integration

# Controls when the action will run. Triggers the workflow on push
on: push

jobs:
  aws-test:
    name: Turn EC2 Instance ON
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-1

    - name: Turn instance ON
      run: |
        aws ec2 start-instances --instance-ids i-077c0adbba49452c0
